version: "3.7"

services:
    php:
        container_name: laravel_boilerplate_php
        build:
            context: ./docker/php
            args:
                - TZ=${TZ}
        volumes:
            - ./src:/var/www/html
            - ./docker/php/php.ini:/usr/local/php/php.ini
        working_dir: /var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_DATABASE=${DB_NAME}
            - DB_USERNAME=${DB_USER}
            - DB_PASSWORD=${DB_PASS}
            - TZ=${TZ}

    nginx:
        container_name: laravel_boilerplate_nginx
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - TZ=${TZ}
        restart: always
        depends_on:
            - php

    db:
        container_name: laravel_boilerplate_mysql
        build: ./docker/mysql
        volumes:
            - ./docker/mysql/db-store:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - TZ=${TZ}
        restart: always
        depends_on:
            - php

    phpmyadmin:
        container_name: laravel_boilerplate_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8888:80
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db
            - PMA_USER=${DB_USER}
            - PMA_PASSWORD=${DB_PASS}
        depends_on:
            - db
volumes:
    db-store:
